name: Linting & Code Quality
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry --user
        python -m poetry install --with dev

    - name: Run Pre-Commit
      run: |
        python -m poetry run pre-commit run --all-files
